// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2DcHoq1UHIl_W0r1BAYbuFVR7K5YJyI',
    appId: '1:544468561370:android:44424465dec562f8bba4e3',
    messagingSenderId: '544468561370',
    projectId: 'projekt-pum',
    storageBucket: 'projekt-pum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97L7Q_UYRaXf7vLNCrWP3PzdCNpT2ndA',
    appId: '1:544468561370:ios:18502625773f9972bba4e3',
    messagingSenderId: '544468561370',
    projectId: 'projekt-pum',
    storageBucket: 'projekt-pum.appspot.com',
    androidClientId: '544468561370-oqamfqvaej2fphvh4rdcpmlkbqlfij1i.apps.googleusercontent.com',
    iosClientId: '544468561370-bj70ldqdvk72vpu1r1ek47giafcrimpd.apps.googleusercontent.com',
    iosBundleId: 'com.miczek.projektpum',
  );
}
